
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compila_flex;

import java.io.*;
import java_cup.runtime.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class AnalizadorSIntactico extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public AnalizadorSIntactico() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public AnalizadorSIntactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSIntactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\074\000\002\002\004\000\002\002\007\000\002\013" +
    "\006\000\002\020\017\000\002\017\020\000\002\007\004" +
    "\000\002\007\004\000\002\007\004\000\002\007\002\000" +
    "\002\010\004\000\002\010\003\000\002\015\010\000\002" +
    "\015\003\000\002\015\003\000\002\015\003\000\002\015" +
    "\006\000\002\015\003\000\002\015\003\000\002\015\003" +
    "\000\002\031\007\000\002\031\007\000\002\031\007\000" +
    "\002\031\007\000\002\032\011\000\002\006\003\000\002" +
    "\006\003\000\002\006\003\000\002\006\003\000\002\011" +
    "\003\000\002\011\003\000\002\016\005\000\002\016\005" +
    "\000\002\016\004\000\002\012\015\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\003\012\000\002" +
    "\014\010\000\002\014\006\000\002\014\002\000\002\026" +
    "\011\000\002\027\010\000\002\027\010\000\002\027\006" +
    "\000\002\004\003\000\002\004\005\000\002\021\003\000" +
    "\002\021\004\000\002\021\005\000\002\022\003\000\002" +
    "\022\005\000\002\024\003\000\002\024\006\000\002\024" +
    "\003\000\002\024\005\000\002\024\004\000\002\023\003" +
    "\000\002\025\003\000\002\025\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\250\000\004\037\005\001\002\000\004\002\252\001" +
    "\002\000\004\040\006\001\002\000\004\016\007\001\002" +
    "\000\032\003\024\017\ufff9\025\026\026\020\027\014\032" +
    "\032\036\021\041\030\050\015\053\031\054\022\055\025" +
    "\001\002\000\036\003\024\014\ufff9\017\ufff9\025\026\026" +
    "\020\027\014\032\032\036\021\041\030\047\ufff9\050\015" +
    "\053\031\054\022\055\025\001\002\000\036\003\ufff0\014" +
    "\ufff0\017\ufff0\025\ufff0\026\ufff0\027\ufff0\032\ufff0\036\ufff0" +
    "\041\ufff0\047\ufff0\050\ufff0\053\ufff0\054\ufff0\055\ufff0\001" +
    "\002\000\036\003\uffef\014\uffef\017\uffef\025\uffef\026\uffef" +
    "\027\uffef\032\uffef\036\uffef\041\uffef\047\uffef\050\uffef\053" +
    "\uffef\054\uffef\055\uffef\001\002\000\036\003\ufff1\014\ufff1" +
    "\017\ufff1\025\ufff1\026\ufff1\027\ufff1\032\ufff1\036\ufff1\041" +
    "\ufff1\047\ufff1\050\ufff1\053\ufff1\054\ufff1\055\ufff1\001\002" +
    "\000\004\011\230\001\002\000\004\015\225\001\002\000" +
    "\004\017\224\001\002\000\036\003\ufff4\014\ufff4\017\ufff4" +
    "\025\ufff4\026\ufff4\027\ufff4\032\ufff4\036\ufff4\041\ufff4\047" +
    "\ufff4\050\ufff4\053\ufff4\054\ufff4\055\ufff4\001\002\000\020" +
    "\011\171\022\166\024\047\034\045\035\046\042\175\050" +
    "\172\001\002\000\012\004\077\005\074\006\075\007\076" +
    "\001\002\000\004\011\140\001\002\000\036\003\ufff3\014" +
    "\ufff3\017\ufff3\025\ufff3\026\ufff3\027\ufff3\032\ufff3\036\ufff3" +
    "\041\ufff3\047\ufff3\050\ufff3\053\ufff3\054\ufff3\055\ufff3\001" +
    "\002\000\036\003\024\014\ufff9\017\ufff9\025\026\026\020" +
    "\027\014\032\032\036\021\041\030\047\ufff9\050\015\053" +
    "\031\054\022\055\025\001\002\000\004\011\131\001\002" +
    "\000\004\011\114\001\002\000\036\003\ufff5\014\ufff5\017" +
    "\ufff5\025\ufff5\026\ufff5\027\ufff5\032\ufff5\036\ufff5\041\ufff5" +
    "\047\ufff5\050\ufff5\053\ufff5\054\ufff5\055\ufff5\001\002\000" +
    "\012\004\077\005\074\006\075\007\076\001\002\000\004" +
    "\011\065\001\002\000\004\011\035\001\002\000\036\003" +
    "\024\014\ufff9\017\ufff9\025\026\026\020\027\014\032\032" +
    "\036\021\041\030\047\ufff9\050\015\053\031\054\022\055" +
    "\025\001\002\000\010\014\ufffc\017\ufffc\047\ufffc\001\002" +
    "\000\004\050\036\001\002\000\004\012\037\001\002\000" +
    "\004\040\040\001\002\000\006\045\043\046\041\001\002" +
    "\000\004\013\062\001\002\000\004\033\061\001\002\000" +
    "\012\024\047\034\045\035\046\050\044\001\002\000\004" +
    "\013\055\001\002\000\022\010\uffdf\012\uffdf\013\uffdf\020" +
    "\uffdf\021\uffdf\022\uffdf\023\uffdf\040\uffdf\001\002\000\022" +
    "\010\uffdd\012\uffdd\013\uffdd\020\uffdd\021\uffdd\022\uffdd\023" +
    "\uffdd\040\uffdd\001\002\000\022\010\uffde\012\uffde\013\uffde" +
    "\020\uffde\021\uffde\022\uffde\023\uffde\040\uffde\001\002\000" +
    "\004\013\051\001\002\000\032\003\024\014\ufff9\025\026" +
    "\026\020\027\014\032\032\036\021\041\030\050\015\053" +
    "\031\054\022\055\025\001\002\000\004\014\053\001\002" +
    "\000\006\045\043\046\041\001\002\000\004\033\uffd6\001" +
    "\002\000\032\003\024\014\ufff9\025\026\026\020\027\014" +
    "\032\032\036\021\041\030\050\015\053\031\054\022\055" +
    "\025\001\002\000\004\014\057\001\002\000\006\045\043" +
    "\046\041\001\002\000\004\033\uffd7\001\002\000\036\003" +
    "\uffd8\014\uffd8\017\uffd8\025\uffd8\026\uffd8\027\uffd8\032\uffd8" +
    "\036\uffd8\041\uffd8\047\uffd8\050\uffd8\053\uffd8\054\uffd8\055" +
    "\uffd8\001\002\000\032\003\024\014\ufff9\025\026\026\020" +
    "\027\014\032\032\036\021\041\030\050\015\053\031\054" +
    "\022\055\025\001\002\000\004\014\064\001\002\000\004" +
    "\033\uffd5\001\002\000\012\024\047\034\045\035\046\050" +
    "\066\001\002\000\004\012\072\001\002\000\004\012\070" +
    "\001\002\000\004\010\071\001\002\000\036\003\uffed\014" +
    "\uffed\017\uffed\025\uffed\026\uffed\027\uffed\032\uffed\036\uffed" +
    "\041\uffed\047\uffed\050\uffed\053\uffed\054\uffed\055\uffed\001" +
    "\002\000\004\010\073\001\002\000\036\003\uffee\014\uffee" +
    "\017\uffee\025\uffee\026\uffee\027\uffee\032\uffee\036\uffee\041" +
    "\uffee\047\uffee\050\uffee\053\uffee\054\uffee\055\uffee\001\002" +
    "\000\004\050\uffe8\001\002\000\004\050\uffe7\001\002\000" +
    "\004\050\uffe6\001\002\000\004\050\uffe9\001\002\000\004" +
    "\050\101\001\002\000\006\010\105\015\104\001\002\000" +
    "\036\003\uffff\014\uffff\017\uffff\025\uffff\026\uffff\027\uffff" +
    "\032\uffff\036\uffff\041\uffff\047\uffff\050\uffff\053\uffff\054" +
    "\uffff\055\uffff\001\002\000\036\003\uffe4\014\uffe4\017\uffe4" +
    "\025\uffe4\026\uffe4\027\uffe4\032\uffe4\036\uffe4\041\uffe4\047" +
    "\uffe4\050\uffe4\053\uffe4\054\uffe4\055\uffe4\001\002\000\012" +
    "\024\047\034\045\035\046\050\110\001\002\000\036\003" +
    "\uffe5\014\uffe5\017\uffe5\025\uffe5\026\uffe5\027\uffe5\032\uffe5" +
    "\036\uffe5\041\uffe5\047\uffe5\050\uffe5\053\uffe5\054\uffe5\055" +
    "\uffe5\001\002\000\004\010\107\001\002\000\036\003\uffe1" +
    "\014\uffe1\017\uffe1\025\uffe1\026\uffe1\027\uffe1\032\uffe1\036" +
    "\uffe1\041\uffe1\047\uffe1\050\uffe1\053\uffe1\054\uffe1\055\uffe1" +
    "\001\002\000\004\010\113\001\002\000\004\010\112\001" +
    "\002\000\036\003\uffe3\014\uffe3\017\uffe3\025\uffe3\026\uffe3" +
    "\027\uffe3\032\uffe3\036\uffe3\041\uffe3\047\uffe3\050\uffe3\053" +
    "\uffe3\054\uffe3\055\uffe3\001\002\000\036\003\uffe2\014\uffe2" +
    "\017\uffe2\025\uffe2\026\uffe2\027\uffe2\032\uffe2\036\uffe2\041" +
    "\uffe2\047\uffe2\050\uffe2\053\uffe2\054\uffe2\055\uffe2\001\002" +
    "\000\004\050\115\001\002\000\004\043\116\001\002\000" +
    "\004\034\117\001\002\000\004\044\120\001\002\000\004" +
    "\044\121\001\002\000\004\044\122\001\002\000\004\034" +
    "\123\001\002\000\004\012\124\001\002\000\004\040\125" +
    "\001\002\000\004\013\126\001\002\000\032\003\024\014" +
    "\ufff9\025\026\026\020\027\014\032\032\036\021\041\030" +
    "\050\015\053\031\054\022\055\025\001\002\000\004\014" +
    "\130\001\002\000\036\003\ufffd\014\ufffd\017\ufffd\025\ufffd" +
    "\026\ufffd\027\ufffd\032\ufffd\036\ufffd\041\ufffd\047\ufffd\050" +
    "\ufffd\053\ufffd\054\ufffd\055\ufffd\001\002\000\004\050\132" +
    "\001\002\000\004\020\133\001\002\000\004\050\134\001" +
    "\002\000\004\012\135\001\002\000\004\010\136\001\002" +
    "\000\036\003\uffea\014\uffea\017\uffea\025\uffea\026\uffea\027" +
    "\uffea\032\uffea\036\uffea\041\uffea\047\uffea\050\uffea\053\uffea" +
    "\054\uffea\055\uffea\001\002\000\010\014\ufffa\017\ufffa\047" +
    "\ufffa\001\002\000\012\024\047\034\045\035\046\050\141" +
    "\001\002\000\004\012\145\001\002\000\004\012\143\001" +
    "\002\000\004\010\144\001\002\000\036\003\uffeb\014\uffeb" +
    "\017\uffeb\025\uffeb\026\uffeb\027\uffeb\032\uffeb\036\uffeb\041" +
    "\uffeb\047\uffeb\050\uffeb\053\uffeb\054\uffeb\055\uffeb\001\002" +
    "\000\004\010\146\001\002\000\036\003\uffec\014\uffec\017" +
    "\uffec\025\uffec\026\uffec\027\uffec\032\uffec\036\uffec\041\uffec" +
    "\047\uffec\050\uffec\053\uffec\054\uffec\055\uffec\001\002\000" +
    "\004\050\150\001\002\000\004\011\151\001\002\000\014" +
    "\004\077\005\074\006\075\007\076\050\152\001\002\000" +
    "\004\012\ufff7\001\002\000\004\050\165\001\002\000\004" +
    "\012\155\001\002\000\004\016\156\001\002\000\032\003" +
    "\024\025\026\026\020\027\014\032\032\036\021\041\030" +
    "\047\ufff9\050\015\053\031\054\022\055\025\001\002\000" +
    "\004\047\160\001\002\000\004\011\161\001\002\000\014" +
    "\004\077\005\074\006\075\007\076\050\152\001\002\000" +
    "\004\012\163\001\002\000\004\017\164\001\002\000\036" +
    "\003\ufffe\014\ufffe\017\ufffe\025\ufffe\026\ufffe\027\ufffe\032" +
    "\ufffe\036\ufffe\041\ufffe\047\ufffe\050\ufffe\053\ufffe\054\ufffe" +
    "\055\ufffe\001\002\000\004\012\ufff8\001\002\000\016\011" +
    "\uffc8\024\uffc8\034\uffc8\035\uffc8\042\uffc8\050\uffc8\001\002" +
    "\000\022\010\uffcb\012\uffcb\013\uffcb\020\uffcb\021\uffcb\022" +
    "\uffcb\023\uffcb\040\uffcb\001\002\000\022\010\uffd2\012\uffd2" +
    "\013\uffd2\020\uffd2\021\uffd2\022\uffd2\023\203\040\uffd2\001" +
    "\002\000\020\011\171\022\166\024\047\034\045\035\046" +
    "\042\175\050\172\001\002\000\024\010\uffcd\011\214\012" +
    "\uffcd\013\uffcd\020\uffcd\021\uffcd\022\uffcd\023\uffcd\040\uffcd" +
    "\001\002\000\004\040\210\001\002\000\022\010\uffcf\012" +
    "\uffcf\013\uffcf\020\uffcf\021\uffcf\022\uffcf\023\uffcf\040\uffcf" +
    "\001\002\000\016\011\171\024\047\034\045\035\046\042" +
    "\175\050\172\001\002\000\016\011\171\024\047\034\045" +
    "\035\046\042\175\050\172\001\002\000\020\010\uffd4\012" +
    "\uffd4\013\uffd4\020\uffd4\021\200\022\201\040\uffd4\001\002" +
    "\000\020\011\171\022\166\024\047\034\045\035\046\042" +
    "\175\050\172\001\002\000\016\011\171\024\047\034\045" +
    "\035\046\042\175\050\172\001\002\000\022\010\uffd0\012" +
    "\uffd0\013\uffd0\020\uffd0\021\uffd0\022\uffd0\023\203\040\uffd0" +
    "\001\002\000\016\011\171\024\047\034\045\035\046\042" +
    "\175\050\172\001\002\000\022\010\uffce\012\uffce\013\uffce" +
    "\020\uffce\021\uffce\022\uffce\023\uffce\040\uffce\001\002\000" +
    "\014\010\uffd3\012\uffd3\013\uffd3\020\uffd3\040\uffd3\001\002" +
    "\000\022\010\uffd1\012\uffd1\013\uffd1\020\uffd1\021\uffd1\022" +
    "\uffd1\023\203\040\uffd1\001\002\000\022\010\uffc9\012\uffc9" +
    "\013\uffc9\020\uffc9\021\uffc9\022\uffc9\023\uffc9\040\uffc9\001" +
    "\002\000\004\013\211\001\002\000\024\025\026\026\020" +
    "\027\014\032\032\041\030\050\015\053\031\054\022\055" +
    "\025\001\002\000\004\014\213\001\002\000\036\003\ufff6" +
    "\014\ufff6\017\ufff6\025\ufff6\026\ufff6\027\ufff6\032\ufff6\036" +
    "\ufff6\041\ufff6\047\ufff6\050\ufff6\053\ufff6\054\ufff6\055\ufff6" +
    "\001\002\000\020\011\171\022\166\024\047\034\045\035" +
    "\046\042\175\050\172\001\002\000\006\012\uffc7\020\uffc7" +
    "\001\002\000\006\012\220\020\217\001\002\000\020\011" +
    "\171\022\166\024\047\034\045\035\046\042\175\050\172" +
    "\001\002\000\022\010\uffcc\012\uffcc\013\uffcc\020\uffcc\021" +
    "\uffcc\022\uffcc\023\uffcc\040\uffcc\001\002\000\006\012\uffc6" +
    "\020\uffc6\001\002\000\004\012\223\001\002\000\022\010" +
    "\uffca\012\uffca\013\uffca\020\uffca\021\uffca\022\uffca\023\uffca" +
    "\040\uffca\001\002\000\004\002\000\001\002\000\020\011" +
    "\171\022\166\024\047\034\045\035\046\042\175\050\172" +
    "\001\002\000\004\010\227\001\002\000\036\003\ufff2\014" +
    "\ufff2\017\ufff2\025\ufff2\026\ufff2\027\ufff2\032\ufff2\036\ufff2" +
    "\041\ufff2\047\ufff2\050\ufff2\053\ufff2\054\ufff2\055\ufff2\001" +
    "\002\000\020\011\171\022\166\024\047\034\045\035\046" +
    "\042\175\050\172\001\002\000\004\012\232\001\002\000" +
    "\004\013\233\001\002\000\024\025\026\026\020\027\014" +
    "\032\032\041\030\050\015\053\031\054\022\055\025\001" +
    "\002\000\004\014\235\001\002\000\042\003\uffd9\014\uffd9" +
    "\017\uffd9\025\uffd9\026\uffd9\027\uffd9\030\240\031\237\032" +
    "\uffd9\036\uffd9\041\uffd9\047\uffd9\050\uffd9\053\uffd9\054\uffd9" +
    "\055\uffd9\001\002\000\036\003\uffdc\014\uffdc\017\uffdc\025" +
    "\uffdc\026\uffdc\027\uffdc\032\uffdc\036\uffdc\041\uffdc\047\uffdc" +
    "\050\uffdc\053\uffdc\054\uffdc\055\uffdc\001\002\000\004\013" +
    "\246\001\002\000\020\011\171\022\166\024\047\034\045" +
    "\035\046\042\175\050\172\001\002\000\004\013\242\001" +
    "\002\000\024\025\026\026\020\027\014\032\032\041\030" +
    "\050\015\053\031\054\022\055\025\001\002\000\004\014" +
    "\244\001\002\000\042\003\uffd9\014\uffd9\017\uffd9\025\uffd9" +
    "\026\uffd9\027\uffd9\030\240\031\237\032\uffd9\036\uffd9\041" +
    "\uffd9\047\uffd9\050\uffd9\053\uffd9\054\uffd9\055\uffd9\001\002" +
    "\000\036\003\uffdb\014\uffdb\017\uffdb\025\uffdb\026\uffdb\027" +
    "\uffdb\032\uffdb\036\uffdb\041\uffdb\047\uffdb\050\uffdb\053\uffdb" +
    "\054\uffdb\055\uffdb\001\002\000\024\025\026\026\020\027" +
    "\014\032\032\041\030\050\015\053\031\054\022\055\025" +
    "\001\002\000\004\014\250\001\002\000\036\003\uffda\014" +
    "\uffda\017\uffda\025\uffda\026\uffda\027\uffda\032\uffda\036\uffda" +
    "\041\uffda\047\uffda\050\uffda\053\uffda\054\uffda\055\uffda\001" +
    "\002\000\010\014\ufffb\017\ufffb\047\ufffb\001\002\000\004" +
    "\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\250\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\024\003\022\007\015" +
    "\013\026\015\032\017\016\020\007\026\012\031\010\032" +
    "\011\001\001\000\024\003\022\007\250\013\026\015\032" +
    "\017\016\020\007\026\012\031\010\032\011\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\016\004\172\005\166\021\176\022\167\023\175" +
    "\024\173\001\001\000\004\006\146\001\001\000\002\001" +
    "\001\000\002\001\001\000\024\003\022\007\136\013\026" +
    "\015\032\017\016\020\007\026\012\031\010\032\011\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\006\077\001\001\000\002\001\001\000\002\001" +
    "\001\000\024\003\022\007\033\013\026\015\032\017\016" +
    "\020\007\026\012\031\010\032\011\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\027\041\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\005\047\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\024\003\022\007\051\013\026\015\032\017\016" +
    "\020\007\026\012\031\010\032\011\001\001\000\002\001" +
    "\001\000\004\027\053\001\001\000\002\001\001\000\024" +
    "\003\022\007\055\013\026\015\032\017\016\020\007\026" +
    "\012\031\010\032\011\001\001\000\002\001\001\000\004" +
    "\027\057\001\001\000\002\001\001\000\002\001\001\000" +
    "\024\003\022\007\062\013\026\015\032\017\016\020\007" +
    "\026\012\031\010\032\011\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\066\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\011\101\016\102\030\105\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\005\110\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\024\003\022\007\126\013\026\015\032\017" +
    "\016\020\007\026\012\031\010\032\011\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\005\141\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\006\152\010\153" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\024\003\022\007\156\013\026" +
    "\015\032\017\016\020\007\026\012\031\010\032\011\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\006\152" +
    "\010\161\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\004\221\005\166\021" +
    "\176\022\167\023\175\024\173\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\005\166\024" +
    "\206\001\001\000\010\005\166\022\205\024\173\001\001" +
    "\000\002\001\001\000\016\004\204\005\166\021\176\022" +
    "\167\023\175\024\173\001\001\000\010\005\166\022\201" +
    "\024\173\001\001\000\002\001\001\000\006\005\166\024" +
    "\203\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\020\003" +
    "\022\013\026\015\211\017\016\026\012\031\010\032\011" +
    "\001\001\000\002\001\001\000\002\001\001\000\020\004" +
    "\214\005\166\021\176\022\167\023\175\024\173\025\215" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\004" +
    "\220\005\166\021\176\022\167\023\175\024\173\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\004\225\005\166" +
    "\021\176\022\167\023\175\024\173\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\004\230\005\166\021\176" +
    "\022\167\023\175\024\173\001\001\000\002\001\001\000" +
    "\002\001\001\000\020\003\022\013\026\015\233\017\016" +
    "\026\012\031\010\032\011\001\001\000\002\001\001\000" +
    "\004\014\235\001\001\000\002\001\001\000\002\001\001" +
    "\000\016\004\240\005\166\021\176\022\167\023\175\024" +
    "\173\001\001\000\002\001\001\000\020\003\022\013\026" +
    "\015\242\017\016\026\012\031\010\032\011\001\001\000" +
    "\002\001\001\000\004\014\244\001\001\000\002\001\001" +
    "\000\020\003\022\013\026\015\246\017\016\026\012\031" +
    "\010\032\011\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSIntactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSIntactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSIntactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public static Nodo arbol;
         /**
     * Método al que se llama automáticamente ante algún error sintactico.
     **/ 
    public void syntax_error(Symbol s){ 
       System.out.println("Error Sintáctico en la Columna " + (s.left) +
        " linear "+s.right+ ". No se esperaba este componente: " +s.value+".");
       System.out.println("Sintaxis malo malo malo");
    } 

    /**
     * Método al que se llama automáticamente ante algún error sintáctico 
     * en el que ya no es posible una recuperación de errores.
     **/ 
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
        System.out.println("Error síntactico irrecuperable en la columna " + 
        (s.left)+ " linear "+s.right+". Componente " + s.value + 
        " no reconocido.");
        System.out.println("Sintaxis MAL irrecuperable"); 
    }  
    


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$AnalizadorSIntactico$actions {


    Nodo arbol;
    int token=0;
    int parNum=0;

  private final AnalizadorSIntactico parser;

  /** Constructor */
  CUP$AnalizadorSIntactico$actions(AnalizadorSIntactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSIntactico$do_action_part00000000(
    int                        CUP$AnalizadorSIntactico$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSIntactico$parser,
    java.util.Stack            CUP$AnalizadorSIntactico$stack,
    int                        CUP$AnalizadorSIntactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSIntactico$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSIntactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSIntactico$parser.done_parsing();
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Program ::= START FLECHA BRACKETA body BRACKETC 
            {
              Object RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).value;
		
    token ++;
    Nodo start = new Nodo("Start",null,token);
    token ++;
    Nodo flecha = new Nodo("flecha",null,token);
    token ++;
    Nodo Braca = new Nodo("Bracket izquierdo",null,token);
    token ++;
    Nodo Bracc = new Nodo("Bracket derecho",null,token);
    start.addHijo(flecha);
    start.addHijo(Braca);
    start.addHijo(Bracc);
    //start.addHijo((Nodo)b);
    //start.print();
    //start.escribirArchivo("]");
    parser.arbol = start;
    //RESULT = node;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("Program",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // declara_simple ::= VAR type ID declara_puntoc 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-2)).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSIntactico$stack.peek()).value;
		
    //no estoy seguro de como declarar id
    token++;
    Nodo decla = new Nodo("Declaracion",null,token);
    decla.addHijo((Nodo)t);
    decla.addHijo((Nodo)d);
    
    token++;
    Nodo node = new Nodo("Id",null,token);
    decla.addHijo(node);
    RESULT = node;

    

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("declara_simple",9, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // funciones ::= FUNC type ID PARENTESISA parametro PARENTESISC BRACKETA body REPLY PARENTESISA parametro PARENTESISC BRACKETC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("funciones",14, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-12)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // CicloFor ::= FOR PARENTESISA ID IN NUM PUNTO PUNTO PUNTO NUM PARENTESISC FLECHA ABRIRC body CERRARC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("CicloFor",13, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-13)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // body ::= proposition body 
            {
              Object RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).right;
		Object p = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSIntactico$stack.peek()).value;
		
    token++;
    Nodo node = new Nodo("Body",null,0);
    node.addHijo((Nodo)p);
    node.addHijo((Nodo)b);
    RESULT = node;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("body",5, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // body ::= funciones body 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSIntactico$stack.peek()).value;
		
    token++;
    Nodo node = new Nodo("Body",null,0);
    node.addHijo((Nodo)b);
    node.addHijo((Nodo)f);
    RESULT = node;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("body",5, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // body ::= error body 
            {
              Object RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSIntactico$stack.peek()).value;
		
    token++;
    Nodo node = new Nodo("Body",null,0);
    node.addHijo("Error",token);
    node.addHijo((Nodo)b);
    RESULT = node;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("body",5, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // body ::= 
            {
              Object RESULT =null;
		
              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("body",5, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // parametro ::= type ID 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("parametro",6, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // parametro ::= ID 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("parametro",6, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // proposition ::= WLE expression FLECHA ABRIRC proposition CERRARC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("proposition",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // proposition ::= declara_simple 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()).right;
		Object d = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSIntactico$stack.peek()).value;
		
    token++;
    Nodo node = new Nodo("Proposicion",null,token);
    node.addHijo("Error",token);
    node.addHijo((Nodo)d);
    RESULT = node;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("proposition",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // proposition ::= CicloFor 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("proposition",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // proposition ::= ifState 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("proposition",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // proposition ::= ID ASSIGNMENT expression PUNTOC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("proposition",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // proposition ::= block_switch 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("proposition",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // proposition ::= print 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("proposition",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // proposition ::= catch 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("proposition",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // print ::= THROW PARENTESISA ID PARENTESISC PUNTOC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("print",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // print ::= THROW PARENTESISA valores PARENTESISC PUNTOC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("print",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // print ::= THROWDOWN PARENTESISA ID PARENTESISC PUNTOC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("print",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // print ::= THROWDOWN PARENTESISA valores PARENTESISC PUNTOC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("print",23, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // catch ::= CATCH PARENTESISA ID COMMA ID PARENTESISC PUNTOC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("catch",24, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-6)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // type ::= VERDAD 
            {
              Object RESULT =null;
		
    token++;
    Nodo node = new Nodo("Verdad", null, token);
    RESULT = node;
    

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // type ::= NUMERITO 
            {
              Object RESULT =null;
		
    token++;
    Nodo node = new Nodo("Numero", null, token);
    RESULT = node;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // type ::= LETRA 
            {
              Object RESULT =null;
		
    token++;
    Nodo node = new Nodo("Char", null, token);
    RESULT = node;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // type ::= WORD 
            {
              Object RESULT =null;
		
    token++;
    Nodo node = new Nodo("String", null, token);
    RESULT = node;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("type",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // declara_puntoc ::= PUNTOC 
            {
              Object RESULT =null;
		
    token++;
    Nodo node = new Nodo(";", null, token);
    RESULT = node;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("declara_puntoc",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // declara_puntoc ::= asigna 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("declara_puntoc",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // asigna ::= ASSIGNMENT valores PUNTOC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("asigna",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // asigna ::= ASSIGNMENT ID PUNTOC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("asigna",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // asigna ::= vacio PUNTOC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("asigna",12, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // declara_array ::= VAR ID ASSIGNMENT NEW ARRAY PARENTESISA NUM PARENTESISC BRACKETA type BRACKETC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("declara_array",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-10)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // valores ::= NUM 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("valores",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // valores ::= BOOL 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("valores",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // valores ::= LETTER 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("valores",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // ifState ::= IF PARENTESISA expression PARENTESISC ABRIRC proposition CERRARC eif 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("ifState",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-7)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // eif ::= EIF expression ABRIRC proposition CERRARC eif 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("eif",10, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // eif ::= ELSE ABRIRC proposition CERRARC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("eif",10, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // eif ::= 
            {
              Object RESULT =null;
		
              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("eif",10, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // block_switch ::= BLOCK PARENTESISA ID PARENTESISC FLECHA cases END 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("block_switch",20, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-6)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // cases ::= CASE ID ABRIRC body CERRARC cases 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("cases",21, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // cases ::= CASE valores ABRIRC body CERRARC cases 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("cases",21, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // cases ::= DEFAULT ABRIRC body CERRARC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("cases",21, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expression ::= expression_simple 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("expression",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expression ::= expression_simple OPER expression 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("expression",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expression_simple ::= termino 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("expression_simple",15, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expression_simple ::= signo termino 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("expression_simple",15, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expression_simple ::= expression_simple OPEA_SUM termino 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("expression_simple",15, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // termino ::= factor 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("termino",16, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // termino ::= termino OPEA_MULT factor 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("termino",16, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // factor ::= ID 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("factor",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // factor ::= ID PARENTESISA list_expression PARENTESISC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("factor",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // factor ::= valores 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("factor",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // factor ::= PARENTESISA expression PARENTESISC 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("factor",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // factor ::= NOT factor 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("factor",18, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // signo ::= OPEA_SUM 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("signo",17, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // list_expression ::= expression 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("list_expression",19, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // list_expression ::= list_expression COMMA expression 
            {
              Object RESULT =null;

              CUP$AnalizadorSIntactico$result = parser.getSymbolFactory().newSymbol("list_expression",19, ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.elementAt(CUP$AnalizadorSIntactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSIntactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSIntactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$AnalizadorSIntactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSIntactico$do_action(
    int                        CUP$AnalizadorSIntactico$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSIntactico$parser,
    java.util.Stack            CUP$AnalizadorSIntactico$stack,
    int                        CUP$AnalizadorSIntactico$top)
    throws java.lang.Exception
    {
              return CUP$AnalizadorSIntactico$do_action_part00000000(
                               CUP$AnalizadorSIntactico$act_num,
                               CUP$AnalizadorSIntactico$parser,
                               CUP$AnalizadorSIntactico$stack,
                               CUP$AnalizadorSIntactico$top);
    }
}

}
