
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 14 19:48:20 CST 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int bool = 2;
  public static final int OPEA_SUM = 17;
  public static final int WORD = 29;
  public static final int ASSIGNMENT = 12;
  public static final int letter = 4;
  public static final int CASE = 37;
  public static final int ABRIRC = 10;
  public static final int ARRAY = 40;
  public static final int FOR = 20;
  public static final int PARENTESISC = 9;
  public static final int BRACKETC = 14;
  public static final int PARENTESISA = 8;
  public static final int BRACKETA = 13;
  public static final int NOT = 34;
  public static final int BLOCK = 25;
  public static final int IN = 35;
  public static final int BOOL = 19;
  public static final int COMMA = 15;
  public static final int WLE = 21;
  public static final int NUM = 27;
  public static final int IF = 22;
  public static final int EIF = 23;
  public static final int ID = 6;
  public static final int EOF = 0;
  public static final int NEW = 41;
  public static final int error = 1;
  public static final int START = 31;
  public static final int NADA = 5;
  public static final int FLECHA = 32;
  public static final int OPEA_MULT = 18;
  public static final int ELSE = 24;
  public static final int PUNTO = 36;
  public static final int LETTER = 28;
  public static final int FUNC = 30;
  public static final int DEFAULT = 38;
  public static final int OPER = 16;
  public static final int PUNTOC = 7;
  public static final int END = 26;
  public static final int REPLY = 39;
  public static final int num = 3;
  public static final int VAR = 33;
  public static final int CERRARC = 11;
}

