
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 12 20:53:07 CST 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int bool = 2;
  public static final int OPEA_SUM = 17;
  public static final int WORD = 34;
  public static final int ASSIGNMENT = 12;
  public static final int letter = 4;
  public static final int THROWDOWN = 31;
  public static final int ABRIRC = 10;
  public static final int ARRAY = 21;
  public static final int FOR = 22;
  public static final int PARENTESISC = 9;
  public static final int BRACKETC = 14;
  public static final int PARENTESISA = 8;
  public static final int BRACKETA = 13;
  public static final int NOT = 40;
  public static final int BLOCK = 27;
  public static final int IN = 41;
  public static final int BOOL = 20;
  public static final int COMMA = 15;
  public static final int THROW = 30;
  public static final int WLE = 23;
  public static final int NUM = 32;
  public static final int IF = 24;
  public static final int EIF = 25;
  public static final int ID = 6;
  public static final int EOF = 0;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int START = 36;
  public static final int NADA = 5;
  public static final int FLECHA = 37;
  public static final int OPEA_MULT = 18;
  public static final int ELSE = 26;
  public static final int PUNTO = 42;
  public static final int LETTER = 33;
  public static final int FUNC = 35;
  public static final int OPER = 16;
  public static final int OPEA_MOD = 19;
  public static final int PUNTOC = 7;
  public static final int END = 28;
  public static final int num = 3;
  public static final int VAR = 38;
  public static final int CATCH = 29;
  public static final int CERRARC = 11;
}

